timezone:
  display: Default Timezone
  type: timezones
  max_items: 1
  mode: typeahead
  default: UTC
collection:
  max_items: 1
  mode: select
  type: collections
  display: 'Event Collection'
  icon: collections
  localizable: false
  listable: hidden
  instructions_position: above
  visibility: visible
  replicator_preview: true
  hide_display: false
